export const Tododata = [
    {
      id: "1",
      time: "10:54am",
      bgtext: "New",
      bg: "primary-transparent",
      text: "Work Assigned by Clients ,try to get new work",
      text2: "Sed ut perspiciatis unde omnis iste natus",
      img: require("../../../assets/img/faces/1.jpg"),
      num: "9",
      bgcolor: "primary",
      color: "primary",
    },
    {
      id: "2",
      time: "10:54am",
      bgtext: "completed",
      bg: "primary-transparent",
      text: "voluptatem accusantium dolo laudantium",
      text2: "inventore veritatis et quasi architecto",
      img: require("../../../assets/img/faces/12.jpg"),
      num: "2",
      bgcolor: "primary",
      color: "info",
    },
    {
      id: "3",
      time: "10:54am",
      bgtext: "Pending ",
      bg: "danger-transparent",
      text: "Nemo enim ipsam voluptatem quia voluptas",
      text2: "vero eos et accusamus et iusto odio dignissimos",
      img: require("../../../assets/img/faces/9.jpg"),
      num: "9",
      bgcolor: "danger",
      color: "danger",
    },
    {
      id: "4",
      time: "10:54am",
      bgtext: "completed",
      bg: "primary-transparent",
      text: "Ut enim ad minima veniam nostrum exercitationem",
      text2: "Quis autem vel eum iure reprehenderit qui",
      img: require("../../../assets/img/faces/4.jpg"),
      num: "6",
      bgcolor: "primary",
      color: "info",
    },
    {
      id: "5",
      time: "10:54am",
      bgtext: "Pending ",
      bg: "danger-transparent",
      text: "I must explain to you how all this mistaken",
      text2: "I will give you a complete account of the system",
      img: require("../../../assets/img/faces/15.jpg"),
      num: "7",
      bgcolor: "danger",
      color: "danger",
    },
    {
      id: "6",
      time: "10:54am",
      bgtext: "New",
      bg: "primary-transparent",
      text: "Rationally encounter quences extremely painful",
      text2: "Which of us ever undertakes laborious physical",
      img: require("../../../assets/img/faces/5.jpg"),
      num: "4",
      bgcolor: "primary",
      color: "info",
    },
  ];
