export const Basicdata = [
       {
         type: "Basic",
         price: "0",
         free: "2 Free",
         click: "3",
         data: "1",
       },
       {
         type: "Advanced",
         most: "Most Popular",
         price: "1,299",
         free: "5 Free",
         click: "5",
         data: "3",
       },
       {
         type: "Regular",
         price: "79.9",
         free: "1 Free",
         click: "4",
         data: "2",
       },
       {
         type: "Premium",
         price: "579.9",
         free: " 1 Free",
         click: "5",
         data: "3",
       },
     ];
   
export const Business = [
    {
      type: "Business",
      price: "0",
      free: "2 Free",
      textcolor: "ms-3 tx-14 my-auto",
      storage: "$12",
      className: "d-flex align-items-center p-2 br-5 border",
      tb: "1Tb",
      text: "For Basic Business purpose !",
      textprice: "Best price is $29",
      click: "3",
      data: "1",
      pricecolor: "ms-auto text-dark",
      daly: "$9",
      online: "24/7",
      Email: "$10",
      check: "true",
      checks: "",
      checkemail: "",
    },
    {
      type: "Advanced",
      color: "primary",
      tb: "5Tb",
      storage: "$140",
      textcolor: "ms-3 tx-14 my-auto text-primary",
      className:
        "d-flex align-items-center p-2 br-5 bg-primary-transparent border border-primary",
      text: " For Advanced business purpose !",
      textprice: "Best price is $599",
      most: "New",
      price: "1,299",
      free: "5 Free",
      click: "5",
      data: "3",
      pricecolor: "ms-auto text-primary",
      daly: "$100",
      online: "$245",
      Email: "$154",
      check: "true",
      checks: "true",
      checkemail: "true",
    },
    {
      type: "Regular",
      price: "79.9",
      tb: "2Tb",
      storage: "$29",
      textcolor: "ms-3 tx-14 my-auto",
      className: "d-flex align-items-center p-2 br-5 border",
      free: "1 Free",
      text: "For Regular business purpose !",
      textprice: "Best price is $79",
      click: "4",
      data: "2",
      pricecolor: "ms-auto text-dark",
      daly: "$10",
      online: "$30",
      Email: "$10",
      check: "true",
      checks: "",
      checkemail: "true",
    },
    {
      type: "Premium",
      price: "579.9",
      free: " 1 Free",
      className: "d-flex align-items-center p-2 br-5 border",
      tb: "3Tb",
      storage: "$59",
      textcolor: "ms-3 tx-14 my-auto",
      text: "For Premium business purpose !",
      textprice: "Best price is $129",
      click: "5",
      data: "3",
      pricecolor: "ms-auto text-dark",
      daly: "$20",
      online: "$40",
      Email: "$20",
      check: "true",
      checks: "",
      checkemail:"true",
    },
  ];

export const Monthdata = [
   {
     type: "Basic",
     yearprice: "0",
     Monthprice: "0",
     free: "2 Free",
     click: "3",
     database: "1",
   },
   {
     type: "Advanced",
     most: "Most Popular",
     Monthprice: "129",
     yearprice: "1,299",
     free: "5 Free",
     click: "5",
     database: "3",
   },
   {
     type: "Regular",
     yearprice: "699",
     Monthprice: "79",
     free: "1 Free",
     click: "4",
     database: "2",
   },
   {
     type: "Premium",
     yearprice: "899",
     Monthprice: "59",
     free: "1 Free",
     click: "5",
     database: "3",
   },
 ];
  
    
